### ISSUE TITLE
Could you release a version?

### ISSUE THREAD

**Issue by studyzy** [martinlindhe/base36#3]
If you release a version such as: **v1.0.0**
it will support better in go module.

**Comment by martinlindhe** [comment]
Sure.

Version 1.0.0 was released: https://github.com/martinlindhe/base36/releases/tag/1.0.0

Is this all that is needed for use with go modules?
I still need to learn to use go modules...  :-)

**Comment by studyzy** [comment]
e~~~~
In Go module standard, your version must start with v.
Could you change tag name to v1.0.0 ?

**Comment by martinlindhe** [comment]
Done
