### ISSUE TITLE
Should encode(0) result in 0, not ""?

### ISSUE THREAD

**Issue by buzzfrog** [martinlindhe/base36#4]
Hi
I trying to use your library in an app and sometime I want to encode a 0 and get a 0 back.
/dag

**Comment by martinlindhe** [comment]
Seems reasonable, but I'm not sure it's correct.

Have you seen any other implementations encoding 0 as "0", or any reference supporting this?

**Comment by martinlindhe** [comment]
Looking at sample implementations here

https://en.wikipedia.org/wiki/Base36

Didn't run the code but seems to me like the C and visual basic impl would encode 0 as "0", while the python one would encode 0 as "".

**Comment by buzzfrog** [comment]
Yes, I was looking at the same article. 
Shouldn't we expect the same behavior as when ecoding to hex?

**Comment by martinlindhe** [comment]
Seems fair to me. Would you like to cook up a patch to fix the behavior?
If not, I should get back to this in a few days.

**Comment by buzzfrog** [comment]
I can do it.




Skaffa Outlook för Android







On Sat, Jul 13, 2019 at 1:24 PM +0200, "Martin Lindhe" <notifications@github.com> wrote:












Seems fair to me. Would you like to cook up a patch to fix the behavior?

If not, I should get back to this in a few days.
