### ISSUE TITLE
Simpler solution available?

### ISSUE THREAD

**Issue by cosmotek** [martinlindhe/base36#7]
Just out of curiosity, why not just use this (for at least the integer encoding cases): https://pkg.go.dev/strconv#FormatUint

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
        // encode as base36
	s := strconv.FormatUint(10911, 36)
	fmt.Printf("%s\n", s)
}
```

**Comment by martinlindhe** [comment]
What exactly is simpler here?

The base36 encoder is literally this:

https://github.com/martinlindhe/base36/blob/b1d46dd6210c6b0f646846d66ffb298e24995940/base36.go#L70-L82

If you feel this could be improved, why won't you send a PR and take it from there?

**Comment by cosmotek** [comment]
Well, mostly the fact that as a consumer you could effect a dependency by using the standard library. Nothing wrong with using your package for more complex cases though. 

I'm coming at this as someone who had no exposure to Base36 and saw your package, thinking it was the only option. Might be helpful to mention the standard lib option for really basic cases.

Please don't take any of this as an attack on the project. I was just pointing out something I noticed and figured I would ask if there was a reason to use one over the other. I always appreciate the value of FOSS projects.

**Comment by martinlindhe** [comment]
The thing is that this code was written I don't know how many years ago, and I'm not even sure there was a stdlib API by then.

Your initial question seemed to suggest I would need to stay up to date with changes in the stdlib.

If you feel this is relevant, please open a PR with a README edit.

**Comment by martinlindhe** [comment]
> I'm coming at this as someone who had no exposure to Base36 and saw your package, thinking it was the only option. Might be helpful to mention the standard lib option for really basic cases.

You are right about this. I have added a notice to the README.
